name: uni_store
description: "A app Flutter project about UniStrore product diversity"
version: 1.0.0+1

environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  readmore: ^3.0.0
  flutter_riverpod: ^2.6.1
  http: ^1.2.2
  flutter_slidable: ^3.1.2
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0
  cached_network_image: ^3.4.1
  firebase_database: ^11.2.0
  shared_preferences: ^2.3.5
  flutter_stripe: ^11.3.0
  lottie: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/screens/
    - assets/icons/
    - assets/lotties/
